language: java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_install: if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gradle ; fi

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
  api_key:
    secure: $GITHUB_TOKEN
  file: build/libs/flarequench.jar
  overwrite: true
  provider: releases
  on:
    all_branches: true
    tags: true
  skip_cleanup: true

install:
  - gradle clean
  - gradle build shadowJar

jdk:
  - oraclejdk11

os:
- linux
- osx
# Java on Windows is not yet supported by Travis CI
# - windows