language: java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
  api_key: $GITHUB_TOKEN
  file: build/libs/flarequench-all.jar
  provider: releases
  on:
    branch: master
    tags: true
  skip_cleanup: true

jdk:
  - oraclejdk11

os:
- linux
- osx
- windows